### ISSUE TITLE
(Custom) Keyboard display issues

### ISSUE THREAD

**Issue by joeshaw** [blinksh/blink#80]
I'm running into a couple of different issues surrounding keyboard display in blink.  I am using a custom keyboard, specifically [Google's Gboard](https://itunes.apple.com/us/app/gboard-search.-gifs.-emojis/id1091700242?mt=8), but I am not sure yet if it's specific to custom keyboards or this one in particular.

I will attach a screen recording to the issue so you can see them in action.

I am seeing two issues:

#### Swiping between sessions causes the keyboard to cover the bottom part of the screen

This is 100% reproducible for me.  With two sessions open and some output in each, swiping left and right between two sessions causes the keyboard to slide out and then slide back in.  When slid back in, the terminal does not scroll up, and the bottom is covered by the keyboard.  I have to swipe up to get it back.

This sometimes leads to the second issue...

#### Some gestures seem to hide the keyboard, and getting it back is hard

I have not found an easily reproducible way to get this to happen, but it has happened to me several times in relatively little Blink usage.  Sometimes gestures (swiping left/right with only one session, scrolling up to the top, pinching to adjust font size) causes the keyboard to be hidden.  When this happens, it usually takes several taps on the screen to get the keyboard to come back.

**Comment by joeshaw** [comment]
https://joeshaw.org/dropbox/blink-keyboard.mov is a screen recording in which I encounter both of these.

**Comment by carloscabanero** [comment]
Thanks a lot for this report! It is weird that it is covering the bottom part, or that it requires so many taps to focus, it definitely doesn't happen in the normal keyboard. There might be some type of incompatibility with Google's one, which is also showing the autocomplete. Will download and take a look at it.

**Comment by joeshaw** [comment]
FWIW I also saw the scrolling issue using the stock keyboard when I rotated from landscape to portrait on an iPhone 6S.

**Comment by strowger** [comment]
I have the first issue as well.

**Comment by carloscabanero** [comment]
Slightly different than #101 but provoked by the same event chain that should be fixed on next version.

Please let me know how today's version worked for you and I will proceed to close.

**Comment by strowger** [comment]
I'm reluctant to say 100% that it's fixed, because I used the previous release intensively for several days before the issue suddenly appeared - but it *seems* to be fixed.

Thank you!

**Comment by carloscabanero** [comment]
Closing here, please reopen if you see it again!!

**Comment by joeshaw** [comment]
I still see the issue where it often takes several taps on the viewport to cause the keyboard to slide back in, but this isn't specific to custom keyboards... it also happens with the stock keyboard.  I'll see if I can come up with a good reproduction case and open a new bug for it.

The first issue where the keyboard obscures the viewport is definitely fixed though.

**Comment by carloscabanero** [comment]
Don't bother about the reproduction case. I have been cleaning up the gestures and it should work perfectly now in Release version (I will release to testers at the same time as it gets approved on the AppStore). Let me know if that isn't the case! ;)
